version: '3.4'

services:
  nginx:
    image: nginx
    hostname: 'nginx'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
      - ./logs/:/var/log/nginx/
    ports:
      - '80:80'
    depends_on:
      - vhackswebstore.core.app
    restart: always
  vhackswebstore.core.app:
    image: ${DOCKER_REGISTRY-}vhackswebstorecoreapp
    build:
      context: .
      dockerfile: VHacksWebstore.Core.App/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
    - '5000:5000'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
