// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace VHacksWebstoreML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public float ProductId { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public string UserId { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public float Rating { get; set; }


    }
}
